#Wed Feb 11 21:36:56 IRKT 2026
micronaut:
  application:
    name: micronaut_test_music
  views:
    thymeleaf:
      enabled: true
      cacheable: false
  router:
    static-resources:
      css:
        paths: classpath:static/css
        mapping: /css/**
      images:
        paths: classpath:static/images
        mapping: /images/**
      audio:
        paths: classpath:static/audio
        mapping: /audio/**
      js:
        paths: classpath:static/js
        mapping: /js/**

datasources:
  default:
    url: jdbc:sqlite:./vplay.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
    schema-generate: CREATE  # Liquibase управляет схемой

jpa:
  default:
#    entity-scan:
#      packages: 'micronaut_test_music.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.community.dialect.SQLiteDialect
        show_sql: true
        format_sql: true

liquibase:
  enabled: false
  change-log: classpath:db/changelog/db.changelog-master.yaml

logger:
  levels:
    io.micronaut: DEBUG
#    io.micronaut.context: TRACE
#    io.micronaut.web.router: DEBUG
#    io.micronaut.http.server: DEBUG
#    org.thymeleaf: DEBUG
